require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FloorsController do

  # This should return the minimal set of attributes required to create a valid
  # Floor. As you add validations to Floor, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "number" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FloorsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all floors as @floors" do
      floor = Floor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:floors).should eq([floor])
    end
  end

  describe "GET show" do
    it "assigns the requested floor as @floor" do
      floor = Floor.create! valid_attributes
      get :show, {:id => floor.to_param}, valid_session
      assigns(:floor).should eq(floor)
    end
  end

  describe "GET new" do
    it "assigns a new floor as @floor" do
      get :new, {}, valid_session
      assigns(:floor).should be_a_new(Floor)
    end
  end

  describe "GET edit" do
    it "assigns the requested floor as @floor" do
      floor = Floor.create! valid_attributes
      get :edit, {:id => floor.to_param}, valid_session
      assigns(:floor).should eq(floor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Floor" do
        expect {
          post :create, {:floor => valid_attributes}, valid_session
        }.to change(Floor, :count).by(1)
      end

      it "assigns a newly created floor as @floor" do
        post :create, {:floor => valid_attributes}, valid_session
        assigns(:floor).should be_a(Floor)
        assigns(:floor).should be_persisted
      end

      it "redirects to the created floor" do
        post :create, {:floor => valid_attributes}, valid_session
        response.should redirect_to(Floor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved floor as @floor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Floor.any_instance.stub(:save).and_return(false)
        post :create, {:floor => { "number" => "invalid value" }}, valid_session
        assigns(:floor).should be_a_new(Floor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Floor.any_instance.stub(:save).and_return(false)
        post :create, {:floor => { "number" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested floor" do
        floor = Floor.create! valid_attributes
        # Assuming there are no other floors in the database, this
        # specifies that the Floor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Floor.any_instance.should_receive(:update_attributes).with({ "number" => "1" })
        put :update, {:id => floor.to_param, :floor => { "number" => "1" }}, valid_session
      end

      it "assigns the requested floor as @floor" do
        floor = Floor.create! valid_attributes
        put :update, {:id => floor.to_param, :floor => valid_attributes}, valid_session
        assigns(:floor).should eq(floor)
      end

      it "redirects to the floor" do
        floor = Floor.create! valid_attributes
        put :update, {:id => floor.to_param, :floor => valid_attributes}, valid_session
        response.should redirect_to(floor)
      end
    end

    describe "with invalid params" do
      it "assigns the floor as @floor" do
        floor = Floor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Floor.any_instance.stub(:save).and_return(false)
        put :update, {:id => floor.to_param, :floor => { "number" => "invalid value" }}, valid_session
        assigns(:floor).should eq(floor)
      end

      it "re-renders the 'edit' template" do
        floor = Floor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Floor.any_instance.stub(:save).and_return(false)
        put :update, {:id => floor.to_param, :floor => { "number" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested floor" do
      floor = Floor.create! valid_attributes
      expect {
        delete :destroy, {:id => floor.to_param}, valid_session
      }.to change(Floor, :count).by(-1)
    end

    it "redirects to the floors list" do
      floor = Floor.create! valid_attributes
      delete :destroy, {:id => floor.to_param}, valid_session
      response.should redirect_to(floors_url)
    end
  end

end
